on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp://157.245.98.118
        username: magento
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /var/www/html/pipeline/
        dangerous-clean-slate: false